apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxtips-demo
  labels:
    app: linuxtips-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: linuxtips-demo
  template:
    metadata:
      labels:
        app: linuxtips-demo
    spec:
      containers:
        - name: app
          image: linuxtips/demo:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
